SELECT DISTINCT F1.X, F1.Y 
FROM (SELECT *,  ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) RN FROM Functions) F1 
INNER JOIN (SELECT *,  ROW_NUMBER() OVER (ORDER BY (SELECT NULL)) RN FROM Functions) F2 ON F1.X = F2.Y AND F2.X = F1.Y AND F1.RN <> F2.RN
WHERE F1.X <= F1.Y
ORDER BY F1.X

